---
#
# Ansible tasks for the demo application.
#
# 
# - name: Ensure the app directory is ready
#   file:
#     path:  "{{ app_deploy_path }}"
#     owner: "{{ app_deploy_user }}"
#     group: "{{ app_deploy_group }}"
#     mode: 0775
#     state: directory

- name: Ensure the nginx configuration is installed
  template:
    src:   nginx.conf.j2
    dest:  "/etc/nginx/conf.d/{{ app_name }}.conf"
    owner: root
    group: root
  notify:
    - Restart nginx

- name: Ensure the php-fpm configuration is installed
  template:
    src:   php-fpm.conf.j2
    dest:  "/etc/php-fpm.d/{{ app_name }}.conf"
    owner: root
    group: root
  notify:
    - Restart php-fpm
